# remote_write:
#   - url: http://load-balancer:9009/api/v1/push
# Add X-Scope-OrgID header so that Mimir knows what tenant the remote write data should be stored in.
#     headers:
#       X-Scope-OrgID: demo
multitenancy_enabled: false
target: all,alertmanager,overrides-exporter

# -usage-stats.enabled=false
usage_stats:
  enabled: false

server:
  http_listen_port: 80
  grpc_listen_port: 9095
  log_level: warn

common:
  storage:
    backend: s3
    s3:
      endpoint:          ${MIMIR_S3_ENDPOINT:minio:9000}
      access_key_id:     ${MIMIR_S3_ACCESS_KEY_ID:lgtmp}
      secret_access_key: ${MIMIR_S3_SECRET_ACCESS_KEY:supersecret}
      insecure:          ${MIMIR_S3_INSECURE:true}
      bucket_name:       ${MIMIR_S3_BUCKET:mimir}
      http:
        insecure_skip_verify: true

alertmanager:
  data_dir: /data/alertmanager
  enable_api: true
  external_url: /alertmanager
  fallback_config_file: /etc/mimir/alertmanager-fallback-config.yaml
alertmanager_storage:
  s3:
    bucket_name: mimir-alertmanager

memberlist:
  join_members: [ mimir-memberlist:7946 ]

ingester:
  ring:
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1

blocks_storage:
  s3:
    bucket_name: mimir-blocks
  tsdb:
    dir: /data/ingester
    ship_interval: 1m
    block_ranges_period: [ 2h ]
    retention_period: 3h
  bucket_store:
    index_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached:11211

    chunks_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached:11211

    metadata_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached:11211

ruler:
  rule_path: /data/rules
  enable_api: true
  alertmanager_url: http://localhost/alertmanager
ruler_storage:
  s3:
    bucket_name: mimir-ruler
  cache:
    backend: memcached
    memcached:
      addresses: dns+memcached:11211

compactor:
  compaction_interval: 30s
  data_dir: /tmp/mimir-compactor
  cleanup_interval: 1m
  tenant_cleanup_delay: 1m

limits:
  native_histograms_ingestion_enabled: true
  max_label_names_per_series: 50
  out_of_order_time_window: 1w
  #max_label_value_length: 4096
  # max_lenght_label_name: 4096
  # max_length_label_value: 4096
  # Delete from storage metrics data older than 1 year. 
  # https://grafana.com/docs/mimir/latest/configure/configure-metrics-storage-retention/
  compactor_blocks_retention_period: 1y

overrides_exporter:
  ring:
    enabled: true
    wait_stability_min_duration: 30s

runtime_config:
  file: /etc/mimir/runtime.yaml

