auth_enabled: false

# -reporting.enabled=false
analytics:
 reporting_enabled: false

server:
  http_listen_port: 80
  grpc_listen_port: 9095
  log_level: warn
  log_format: json

common:
  compactor_address: loki
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      bucketnames: loki-data
      endpoint: ${LOKI_S3_ENDPOINT:-minio:9000}
      access_key_id: ${LOKI_S3_ACCESS_KEY_ID:-lgtmp}
      secret_access_key: ${LOKI_S3_SECRET_ACCESS_KEY:-supersecret}
      insecure: ${LOKI_S3_INSECURE:-true}
      s3forcepathstyle: true
      http_config:
        insecure_skip_verify: true

bloom_gateway:
  enabled: true
  client:
    addresses: "dns+loki:9095"
    cache_results: true
    results_cache:
      cache:
        memcached_client:
          addresses: "dns+memcached:11211"

bloom_compactor:
  enabled: true
  ring:
    kvstore:
      store: memberlist

index_gateway:
  mode: simple
compactor:
  working_directory: /tmp/compactor

memberlist:
   join_members:
   - loki-memberlist:7946

# https://github.com/grafana/loki/blob/main/docs/sources/configure/_index.md#query_range
query_range:
  align_queries_with_step: true

  cache_results: true
  results_cache:
    cache:
      memcached_client:
        addresses: "dns+memcached:11211"

  cache_index_stats_results: true
  index_stats_results_cache:
    cache:
      memcached_client:
        addresses: "dns+memcached:11211"
  # cache_volume_results: true
  # cache_series_results: true
  # instant_metric_query_split_align: true
  # cache_instant_metric_results: true
  # instant_metric_results_cache:
  #   cache:
  #     memcached_client:
  #       addresses: "dns+memcached:11211"
  # series_results_cache:
  #   cache:
  #     memcached_client:
  #       addresses: dns+memcached:11211"
  # volume_results_cache:
  #   cache:
  #     memcached_client:
  #       addresses: "dns+memcached:11211"

pattern_ingester:
  enabled: true

limits_config:
  max_global_streams_per_user: 0
  max_cache_freshness_per_query: 10m
  reject_old_samples: false
  reject_old_samples_max_age: 336h
  split_queries_by_interval: 15m
  ingestion_rate_mb: 20000
  ingestion_burst_size_mb: 100000
  allow_structured_metadata: false
  volume_enabled: true

# ingester:
#   max_chunk_age: 48h
  # lifecycler:
  #   ring:
  #     kvstore:
  #       store: inmemory
  #     replication_factor: 1

ingester:
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 30m
  chunk_retain_period: 1m
  max_chunk_age: 48h
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  # max_transfer_retries: 0
  # wal:
  #   dir: /var/loki/wal

ruler:
  storage:
    s3:
      bucketnames: loki-ruler
    type: s3
  # alertmanager_url: http://127.0.0.1:8080/alertmanager
  # ring:
  #   # Quickly detect unhealthy rulers to speed up the tutorial.
  #   heartbeat_period: 2s
  #   heartbeat_timeout: 10s

runtime_config:
  file: /etc/loki/runtime.yaml

schema_config:
  configs:
  - from: "2024-04-08"
    index:
      prefix: loki_index_
      period: 24h
    object_store: s3
    store: tsdb
    schema: v13

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    index_gateway_client:
      server_address: "dns+loki:9095"

chunk_store_config:
  chunk_cache_config:
    memcached_client:
      addresses: "dns+memcached:11211"
