services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    expose:
      - '3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      #- GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./config/grafana:/var/lib/grafana
      #- grafana-storage: {}

    #networks:
      #service
    networks:
      proxy-network:
      observability:
        aliases:
          - grafana-memberlist
