name: observability
include:
  - ./compose-mimir.yml
  - ./compose-loki.yml
  - ./compose-alloy.yml
  - ./compose-grafana.yml

networks:
  proxy-network:
    name: services
    external: true
  observability:
    name: observability
